##########################################################################
#
# EM_PGAdmin portable (green) package builder
#
# Builds EM_PGAdmin_<version>.zip - an unzip-and-run distribution with an
# embedded Python runtime, all dependencies, and the pgAdmin web sources.
#
# Usage:
#   python tools/em/build_portable.py --version 9.18-em1.0.0
#
##########################################################################

import argparse
import os
import shutil
import subprocess
import sys
import urllib.request
import zipfile

PYTHON_EMBED_URL = (
    'https://www.python.org/ftp/python/3.13.3/'
    'python-3.13.3-embed-amd64.zip'
)
GET_PIP_URL = 'https://bootstrap.pypa.io/get-pip.py'

# Directories / patterns not shipped in the portable package.
WEB_EXCLUDE_DIRS = {
    'node_modules', 'regression', '.yarn', '.coverage', 'htmlcov',
    'tools', '.scannerwork', 'pgadmin.static'
}
WEB_EXCLUDE_NAMES = {
    '.gitignore', '.gitattributes', '.eslintrc.js', '.stylelintrc.json',
    'yarn.lock', 'package.json', 'package-lock.json', '.yarnrc.yml',
    'webpack.config.js', 'webpack.shim.js', 'jest.config.js',
    '.babelrc', '.flake8', '.percy.yml', 'tsconfig.json',
    'vitest.config.ts', 'codecov.yml',
}
# Test directories anywhere inside the tree
EXCLUDE_SUBDIR_NAMES = {'tests', '__pycache__', 'node_modules', 'test'}


def download(url, dest):
    if os.path.exists(dest):
        print('Using cached download: {0}'.format(dest))
        return
    print('Downloading {0} ...'.format(url))
    with urllib.request.urlopen(url) as resp, open(dest, 'wb') as f:
        shutil.copyfileobj(resp, f)


def copy_web_sources(src_web, dst_web):
    # NOTE: ignore_patterns match at ANY depth - do not add patterns that
    # collide with package directories inside pgadmin/ (e.g. 'tools'
    # would drop pgadmin/tools).
    shutil.copytree(
        src_web, dst_web,
        ignore=shutil.ignore_patterns(
            'node_modules', 'regression', '__pycache__', '*.pyc',
            '.yarn', '.git*', 'htmlcov', '.scannerwork',
            'yarn.lock', 'package.json', 'jest.config.js',
            'webpack.config.js', 'webpack.shim.js', 'tsconfig.json',
            'vitest.config.ts', '.babelrc', '.stylelintrc.json',
            '.eslintrc.js', '.percy.yml', 'codecov.yml',
            '.coverage', '.nyc_output',
        ))


def setup_runtime(runtime_dir, cache_dir, requirements, extra_reqs=None):
    embed_zip = os.path.join(cache_dir, 'python-embed.zip')
    download(PYTHON_EMBED_URL, embed_zip)

    print('Extracting embedded Python into {0} ...'.format(runtime_dir))
    with zipfile.ZipFile(embed_zip) as zf:
        zf.extractall(runtime_dir)

    # Enable site-packages and a Lib directory next to the interpreter.
    pth_files = [f for f in os.listdir(runtime_dir) if f.endswith('._pth')]
    pth_path = os.path.join(runtime_dir, pth_files[0])
    with open(pth_path, 'w') as f:
        f.write('python313.zip\n')
        f.write('.\n')
        f.write('Lib\\site-packages\n')
        f.write('import site\n')

    get_pip = os.path.join(cache_dir, 'get-pip.py')
    download(GET_PIP_URL, get_pip)

    python_exe = os.path.join(runtime_dir, 'python.exe')

    subprocess.check_call([
        python_exe, get_pip, '--no-warn-script-location', '--quiet'
    ])

    reqs = [requirements]
    if extra_reqs:
        reqs.extend(extra_reqs)
    for req in reqs:
        subprocess.check_call([
            python_exe, '-m', 'pip', 'install', '-r', req,
            '--no-warn-script-location', '--disable-pip-version-check',
        ])


CONFIG_LOCAL = '''\
# EM_PGAdmin portable configuration - keeps everything inside the
# package folder. Generated by tools/em/build_portable.py.
import os

_WEB_DIR = os.path.dirname(os.path.abspath(__file__))
_DATA_DIR = os.path.join(os.path.dirname(_WEB_DIR), 'data')
os.makedirs(_DATA_DIR, exist_ok=True)

SERVER_MODE = False
DEFAULT_SERVER = '127.0.0.1'
DEFAULT_SERVER_PORT = 5050

DATA_DIR = _DATA_DIR
SQLITE_PATH = os.path.join(_DATA_DIR, 'pgadmin.db')
LOG_FILE = os.path.join(_DATA_DIR, 'pgadmin.log')
SESSION_DB_PATH = os.path.join(_DATA_DIR, 'sessions')
STORAGE_DIR = os.path.join(_DATA_DIR, 'storage')
AZURE_CREDENTIAL_CACHE_DIR = os.path.join(_DATA_DIR, 'azure')
KERBEROS_CCACHE_DIR = os.path.join(_DATA_DIR, 'kerberos')

UPGRADE_CHECK_ENABLED = False
'''

START_BAT = '''\
@echo off
rem EM_PGAdmin portable launcher
setlocal
cd /d "%~dp0web"

if not exist "..\\data" mkdir "..\\data"

start "EM_PGAdmin" /min "..\\runtime\\python.exe" "%~dp0web\\pgAdmin4.py"

rem Wait for the server to accept connections, then open the browser.
powershell -NoProfile -Command "$opened=$false; for ($i=0; $i -lt 120; $i++) { try { $c = New-Object Net.Sockets.TcpClient('127.0.0.1', 5050); $c.Close(); $opened=$true; break } catch { Start-Sleep -Milliseconds 500 } }; if ($opened) { Start-Process 'http://127.0.0.1:5050' } else { Write-Host 'pgAdmin failed to start within 60 seconds. Check data\\pgadmin.log' }"
endlocal
'''

STOP_BAT = '''\
@echo off
rem Stops the EM_PGAdmin background server started by 启动pgAdmin.bat
taskkill /FI "WINDOWTITLE eq EM_PGAdmin*" /T >nul 2>&1
if %ERRORLEVEL% == 0 (
  echo EM_PGAdmin stopped.
) else (
  echo EM_PGAdmin server is not running.
)
pause
'''


def zip_dir(src_dir, zip_path):
    print('Creating {0} ...'.format(zip_path))
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED,
                         compresslevel=9) as zf:
        for root, _dirs, files in os.walk(src_dir):
            for file in files:
                full = os.path.join(root, file)
                rel = os.path.relpath(full, os.path.dirname(src_dir))
                zf.write(full, rel)
    size_mb = os.path.getsize(zip_path) / (1024 * 1024)
    print('Done: {0} ({1:.1f} MB)'.format(zip_path, size_mb))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--version', required=True,
                        help='EM version, e.g. 9.18-em1.0.0')
    parser.add_argument('--repo', default=os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    parser.add_argument('--out-dir', default=None)
    parser.add_argument('--cache-dir', default=None)
    parser.add_argument('--skip-zip', action='store_true')
    args = parser.parse_args()

    repo = os.path.abspath(args.repo)
    # Finished zips land in <repo>/release (gitignored) so they are ready
    # to attach to a GitHub Release; staging and the download cache stay
    # out of the way under dist/.
    out_dir = os.path.abspath(args.out_dir or os.path.join(repo, 'release'))
    cache_dir = os.path.abspath(
        args.cache_dir or os.path.join(repo, 'dist', 'cache'))

    pkg_name = 'EM_PGAdmin_{0}'.format(args.version)
    staging = os.path.join(out_dir, pkg_name)

    if os.path.exists(staging):
        print('Removing existing staging dir: {0}'.format(staging))
        shutil.rmtree(staging)
    os.makedirs(staging)
    os.makedirs(cache_dir, exist_ok=True)

    print('== Copying web sources ==')
    copy_web_sources(os.path.join(repo, 'web'), os.path.join(staging, 'web'))

    print('== Setting up embedded Python runtime ==')
    setup_runtime(os.path.join(staging, 'runtime'), cache_dir,
                  os.path.join(repo, 'requirements.txt'))

    print('== Writing portable config and launchers ==')
    with open(os.path.join(staging, 'web', 'config_local.py'), 'w',
              encoding='utf-8') as f:
        f.write(CONFIG_LOCAL)
    with open(os.path.join(staging, '启动pgAdmin.bat'), 'w',
              encoding='gbk') as f:
        f.write(START_BAT)
    with open(os.path.join(staging, '停止pgAdmin.bat'), 'w',
              encoding='gbk') as f:
        f.write(STOP_BAT)

    for extra in ('EM_README.md', 'LICENSE'):
        src = os.path.join(repo, extra)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(staging, extra))

    os.makedirs(os.path.join(staging, 'data'), exist_ok=True)

    if not args.skip_zip:
        zip_dir(staging, os.path.join(out_dir, pkg_name + '.zip'))

    print('Build complete.')


if __name__ == '__main__':
    sys.exit(main())
